const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../../gas/Code.gs'),'utf8');
function env(){const calls=[],values=new Map(),context=vm.createContext({console,Date,JSON,encodeURIComponent,Utilities:{formatDate(d,tz,format){const ps=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(d).map(x=>[x.type,x.value]));if(format==='yyyy-MM-dd')return `${ps.year}-${ps.month}-${ps.day}`;const offset=Math.round((Date.UTC(+ps.year,+ps.month-1,+ps.day,+ps.hour,+ps.minute,+ps.second)-+d)/60000),a=Math.abs(offset);return `${offset<0?'-':'+'}${String(Math.floor(a/60)).padStart(2,'0')}${String(a%60).padStart(2,'0')}`;}},CacheService:{getScriptCache:()=>({get:k=>values.get(k),put:(k,v)=>values.set(k,v),remove:k=>values.delete(k)})},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},ScriptApp:{getOAuthToken:()=> 'fixture-oauth',getScriptId:()=> 'test-script'},UrlFetchApp:{fetch:(url,options)=>{calls.push({url,options});return {getResponseCode:()=>200,getContentText:()=>JSON.stringify({timeSeries:[]})};}},HtmlService:{XFrameOptionsMode:{ALLOWALL:'allow'},createHtmlOutput:html=>({html,setXFrameOptionsMode(mode){this.mode=mode;return this;}})},Logger:{log(){}},PropertiesService:{getScriptProperties:()=>({setProperty(){}})}});vm.runInContext(source,context);return {c:context,calls,values};}
test('backend Pacific periods include DST and agree with the client',()=>{const {c}=env(),m=require('../../firestore-monitor.js');for(const t of ['2026-10-06T21:33:00Z','2026-03-08T15:00:00Z','2026-11-01T15:00:00Z'])assert.deepEqual(JSON.parse(JSON.stringify(c.firestoreDay_(Date.parse(t)))),m.dayWindow(Date.parse(t)));});
test('monitor sums DELTA points across labels and pages only inside the quota day',()=>{const e=env(),now=Date.parse('2026-10-06T21:00:00Z'),day=e.c.firestoreDay_(now);e.c.UrlFetchApp.fetch=(url,o)=>{e.calls.push({url,o});const points=(n,at)=>({value:{int64Value:String(n)},interval:{endTime:new Date(at).toISOString()}});return {getResponseCode:()=>200,getContentText:()=>JSON.stringify(e.calls.length===1?{timeSeries:[{points:[points(10,day.start+60000),points(200,day.start)]},{points:[points(20,day.start+120000)]}],nextPageToken:'page2'}:{timeSeries:[{points:[points(7,day.start+180000)]}]})};};const r=e.c.firestoreMetric_('read',day,now);assert.equal(r.count,37);assert.equal(e.calls.length,2);const u=new URL(e.calls[0].url);assert.match(u.searchParams.get('filter'),/database_id = "\(default\)"/);assert.match(u.searchParams.get('filter'),/project = "futari-list-17396"/);assert.match(u.searchParams.get('filter'),/read_ops_count/);assert.equal(e.calls[0].o.headers.Authorization,'Bearer fixture-oauth');});
test('no monitoring data is unknown rather than zero and responses are cached',()=>{const e=env(),a=e.c.firestoreUsage_(),b=e.c.firestoreUsage_();assert.equal(a.metrics.reads.count,null);assert.equal(e.calls.length,4);assert.equal(b.checkedAt,a.checkedAt);assert.ok(e.calls.every(x=>x.url.startsWith('https://monitoring.googleapis.com/')));assert(!JSON.stringify(a).includes('fixture-oauth'));});
test('missing monitoring scope returns actionable setup state without making a Firestore read',()=>{const e=env();e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>403,getContentText:()=>JSON.stringify({error:{message:'ACCESS_TOKEN_SCOPE_INSUFFICIENT'}})});const r=e.c.firestoreUsage_();assert.equal(r.status,'setup_required');assert.match(r.message,/権限/);assert.equal(r.setupUrl,'https://script.google.com/home/projects/test-script/edit');assert.equal(r.metrics,undefined);});
test('monitor refuses partial query errors instead of understating usage',()=>{const e=env();e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({executionErrors:[{code:13}]})});assert.throws(()=>e.c.firestoreUsage_(),/一部の計測値/);});
test('direct AI validates media and never calls Firestore',()=>{const e=env();let parts;e.c.aiText_=p=>(parts=p,{text:'```json\n{"text":"こんにちは"}\n```'});const r=e.c.aiDirect_({prompt:'文字起こし',img:'AQIDBA==',mime:'audio/mp4;codecs=mp4a.40.2'});assert.equal(r.text,'こんにちは');assert.equal(parts[1].inline_data.mime_type,'audio/mp4');assert.equal(e.calls.length,0);for(const a of [{prompt:''},{prompt:'x',img:'@@@=',mime:'audio/mp4'},{prompt:'x',img:'AQIDBA==',mime:'text/html'}])assert.throws(()=>e.c.aiDirect_(a));});
test('new endpoints require an authenticated registered family member',()=>{const e=env();e.c.verifyUser_=()=> 'intruder@example.test';for(const tool of ['aiDirect','firestoreUsage'])assert.equal(e.c.handle_(JSON.stringify({tool,args:{prompt:'x'}})).error.code,'not_granted');assert.equal(e.calls.length,0);});
test('form reply escapes embedded script content and posts to the fixed application origin',()=>{const e=env();e.c.handle_=()=>({payload:{reply:'</script><script>bad()'}});const r=e.c.firestoreFormReply_({futariRpc:'a'.repeat(32),rpcPayload:'{}'});assert.equal(r.mode,'allow');assert(!r.html.includes('</script><script>'));assert.match(r.html,/https:\/\/rikuouchi-pra.github.io/);assert.match(r.html,/\\u003c/);assert.equal(e.c.firestoreFormReply_({futariRpc:'<bad>'}).mode,undefined);});
test('first setup stages the read-only scope without publishing or changing unrelated scopes',()=>{const e=env(),calls=[],manifest={oauthScopes:['existing-scope']};e.c.sapi_=(method,path,body)=>{calls.push({method,path,body});return {files:[{name:'appsscript',type:'JSON',source:JSON.stringify(manifest)},{name:'Code',type:'SERVER_JS',source:'existing code'}]};};assert.equal(e.c.setupFirestoreMonitoring().needsConsent,true);assert.deepEqual(calls.map(x=>[x.method,x.path]),[['get','/content'],['put','/content']]);const m=JSON.parse(calls[1].body.files[0].source);assert.deepEqual(m.oauthScopes,['existing-scope','https://www.googleapis.com/auth/monitoring.read']);assert.equal(calls[1].body.files[1].source,'existing code');});
test('capacity uses the newest gauge sample across pages, not the sum of historical sizes',()=>{
 const e=env(),now=Date.now(),point=(bytes,offset)=>({value:{int64Value:String(bytes)},interval:{endTime:new Date(now+offset).toISOString()}});
 e.c.UrlFetchApp.fetch=url=>{e.calls.push(url);const u=new URL(url);assert.match(u.searchParams.get('filter'),/storage\/data_and_index_storage_bytes/);assert.equal(Date.parse(u.searchParams.get('interval.startTime')),now-86400000);return {getResponseCode:()=>200,getContentText:()=>JSON.stringify(e.calls.length===1?{timeSeries:[{points:[point(200,-600000),point(500,-60000)]}],nextPageToken:'second'}:{timeSeries:[{points:[point(999,60000),point(900,-120000),point(100,-90000000)]}]})};};
 const r=e.c.firestoreStorage_(now);assert.equal(r.bytes,500);assert.equal(r.lastPointAt,now-60000);assert.equal(e.calls.length,2);
});
test('capacity distinguishes missing data and a measured empty database, and rejects malformed values',()=>{
 const e=env(),now=Date.now();assert.equal(e.c.firestoreStorage_(now).bytes,null);
 const p={interval:{endTime:new Date(now-60000).toISOString()},value:{int64Value:'0'}};e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({timeSeries:[{points:[p]}]})});assert.equal(e.c.firestoreStorage_(now).bytes,0);
 for(const bad of [null,'-1','1.5','9007199254740993']){p.value.int64Value=bad;assert.throws(()=>e.c.firestoreStorage_(now),/形式/);}
});
test('two authenticated family accounts share the same backend cache including capacity',()=>{
 const e=env(),now=Date.now(),r=e.c.firestoreUsage_();assert.equal(r.schema,2);assert.equal(r.metrics.storage.bytes,null);assert.equal(e.calls.length,4);
 for(const email of ['rikurussel14@gmail.com','a1lic3h2dak1@gmail.com']){e.c.verifyUser_=()=>email;const response=e.c.handle_(JSON.stringify({tool:'firestoreUsage',idToken:'fixture-token'}));assert.equal(response.payload.checkedAt,r.checkedAt);}
 assert.equal(e.calls.length,4);assert(!JSON.stringify(r).includes('fixture-token'));
});
test('billing-required errors identify the exact project and do not publish a deployment',()=>{
 const e=env();e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>403,getContentText:()=>JSON.stringify({error:{message:'This API method requires billing to be enabled'}})});
 const r=e.c.firestoreUsage_();assert.equal(r.reason,'billing');assert.equal(r.setupUrl,'https://console.cloud.google.com/billing/enable?project=futari-list-17396');assert.match(r.message,/Firestoreの無料枠超過分/);
 const calls=[];e.c.sapi_=(method,path)=>{calls.push(path);return {files:[{name:'appsscript',type:'JSON',source:JSON.stringify({oauthScopes:['https://www.googleapis.com/auth/monitoring.read']})}]};};assert.throws(()=>e.c.setupFirestoreMonitoring(),/課金/);assert.deepEqual(calls,['/content']);
});
test('quota-day totals do not hide truncated pagination or sum beyond integer precision',()=>{
 const e=env(),now=Date.now(),day=e.c.firestoreDay_(now);e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({nextPageToken:'never-ends'})});assert.throws(()=>e.c.firestoreMetric_('read',day,now),/全件を確認/);
 e.c.UrlFetchApp.fetch=()=>({getResponseCode:()=>200,getContentText:()=>JSON.stringify({timeSeries:[{points:[Number.MAX_SAFE_INTEGER,1].map(n=>({interval:{endTime:new Date(day.start+60000).toISOString()},value:{int64Value:String(n)}}))}]})});assert.throws(()=>e.c.firestoreMetric_('read',day,now),/大きい/);
});
