const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const crypto=require('node:crypto');
const root=require('node:path').resolve(__dirname,'../..');
function env(){
 const props={},files={},docs={},calls=[],triggers=[];let seq=0,status=201;
 const dev='d11111111-1111-4111-8111-111111111111', sec='a'.repeat(72);
 const prop={getProperty:k=>props[k]??null,setProperty(k,v){props[k]=v;return this},getProperties:()=>({...props})};
 const response=(code,data)=>({getResponseCode:()=>code,getContentText:()=>typeof data==='string'?data:JSON.stringify(data)});
 const file=id=>({getId:()=>id,getBlob:()=>({getDataAsString:()=>files[id]}),setContent:s=>{files[id]=s}});
 const folder={createFile(n,s){const id='f'+ ++seq;files[id]=s;return file(id)}};
 const ctx={Uint8Array,Date,Number,Math,JSON,Array,Map,Set,BigInt,TextEncoder,console,MimeType:{PLAIN_TEXT:'text/plain'},Logger:{log(){}},FIREBASE_API_KEY:'public',FIREBASE_PROJECT_ID:'test',AI_USERS:['h@test.example','w@test.example'],err_:(code,s)=>Object.assign(new Error(s),{code}),Utilities:{DigestAlgorithm:{SHA_256:'sha256'},Charset:{UTF_8:'utf8'},computeDigest:(alg,s)=>Array.from(crypto.createHash('sha256').update(s).digest()),newBlob:s=>({getBytes:()=>Array.from(Buffer.from(s))}),getUuid:()=>crypto.randomUUID(),base64EncodeWebSafe:a=>Buffer.from(a).toString('base64url'),base64DecodeWebSafe:s=>Array.from(Buffer.from(s,'base64url'))},PropertiesService:{getScriptProperties:()=>prop},LockService:{getScriptLock:()=>({tryLock:()=>true,releaseLock(){}})},DriveApp:{createFolder:()=>({...folder,getId:()=> 'folder'}),getFolderById:()=>folder,getFileById:file},ScriptApp:{getOAuthToken:()=>crypto.randomBytes(32).toString('hex'),getProjectTriggers:()=>triggers,newTrigger:n=>({timeBased(){return this},everyMinutes(m){assert.equal(m,5);return this},create(){triggers.push({getHandlerFunction:()=>n})}})},UrlFetchApp:{fetch(url,o){calls.push({url,o});if(url.startsWith('https://identitytoolkit.')){const uid=JSON.parse(o.payload).idToken;return response(200,{users:[{localId:uid,email:uid==='uidh'?'h@test.example':'w@test.example'}]});}if(url.startsWith('https://firestore.')){const path=url.split('/documents/')[1];return response(docs[path]?200:404,{fields:{json:{stringValue:JSON.stringify(docs[path])}}});}return response(status,'');}}};
 vm.createContext(ctx);vm.runInContext(fs.readFileSync(root+'/gas/PushCrypto.gs','utf8')+'\n'+fs.readFileSync(root+'/gas/Push.gs','utf8'),ctx);
 ctx.setupPushNotifications();
 function register({id=dev,uid='uidh',role='h',priv=[],shared=[],now=[],op='sync'}={}){docs['push/'+id]={on:true,sub:{endpoint:'https://web.push.apple.com/test-'+id},off:[],shared,now};docs['data/users/'+uid+'/private/push/'+id]={sec,priv};return ctx.push_(uid,role+'@test.example',{op,dev:id,ppath:'data/users/'+uid+'/private/push/'+id});}
 return {ctx,props,files,docs,calls,triggers,dev,sec,register,setStatus:n=>status=n};
}
const msg=(id,role,at=Date.now()+60000,kind='ev')=>({id,roles:[role],at,kind,t:id,b:'body'});
test('VAPID public key and JWT verify independently with Node crypto; cached for six hours',()=>{const e=env();const key=e.ctx.pushKeys_().key;const auth=e.ctx.pushJwt_('https://web.push.apple.com');const jwt=auth.match(/t=([^,]+)/)[1];const parts=jwt.split('.');const pub=Buffer.from(key,'base64url');const jwk={kty:'EC',crv:'P-256',x:pub.subarray(1,33).toString('base64url'),y:pub.subarray(33).toString('base64url')};assert(crypto.verify('sha256',Buffer.from(parts[0]+'.'+parts[1]),{key:crypto.createPublicKey({key:jwk,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));assert.equal(JSON.parse(Buffer.from(parts[1],'base64url')).aud,'https://web.push.apple.com');assert.equal(e.ctx.pushJwt_('https://web.push.apple.com'),auth);assert.equal(e.triggers.length,1);e.ctx.setupPushNotifications();assert.equal(e.triggers.length,1)});
test('rejects arbitrary URLs, credentials, ports and redirects',()=>{const e=env();for(const s of ['http://web.push.apple.com/x','https://web.push.apple.com.evil.test/x','https://web.push.apple.com@evil.test/x','https://127.0.0.1/x','https://fcm.googleapis.com:8080/x','https://web.push.apple.com/x#foo'])assert.throws(()=>e.ctx.pushOrigin_(s));assert.equal(e.ctx.pushOrigin_('https://updates.push.services.mozilla.com/wpush/v2/x'),'https://updates.push.services.mozilla.com')});
test('test push uses valid VAPID and secret-protected one-time inbox; no token stored',()=>{const e=env();assert.equal(e.register({op:'test'}).sent,1);const call=e.calls.find(c=>c.url.startsWith('https://web.push.'));assert.equal(call.o.followRedirects,false);assert.equal(call.o.payload,'');assert.equal(call.o.headers.TTL,'300');assert.equal(e.ctx.pushInbox_(e.dev,'wrong').list.length,0);assert.equal(e.ctx.pushInbox_(e.dev,e.sec).list.length,1);assert.equal(e.ctx.pushInbox_(e.dev,e.sec).list.length,0);assert(!JSON.stringify(e.files).includes('Bearer'));assert(!JSON.stringify(e.props).includes(e.sec));});
test('rejects cross-user private paths and taking over another device',()=>{const e=env();e.register();assert.throws(()=>e.ctx.push_('uidh','h@test.example',{op:'sync',dev:e.dev,ppath:'data/users/uidw/private/push/'+e.dev}),/本人/);assert.throws(()=>e.register({uid:'uidw',role:'w'}),/変更できません/);assert.throws(()=>e.ctx.push_('uidw','w@test.example',{op:'off',dev:e.dev}),/変更できません/)});
test('private reminders never enter partner devices; shared plans replace cancelled entries',()=>{const e=env(),w='d22222222-2222-4222-8222-222222222222';e.register({id:w,uid:'uidw',role:'w',priv:[msg('wife-private','w')]});e.register({priv:[msg('husband-private','h')],shared:[msg('shared-wife','w'),msg('shared-husband','h')]});const wife=e.ctx.pushRead_(w),husband=e.ctx.pushRead_(e.dev);assert.equal(wife.priv[0].id,'wife-private');assert.equal(wife.shared[0].id,'shared-wife');assert.equal(husband.priv[0].id,'husband-private');assert(!JSON.stringify(wife).includes('husband-private'));e.register();assert.equal(e.ctx.pushRead_(w).shared.length,0);assert.equal(e.ctx.pushRead_(w).priv.length,1)});
test('due messages deduplicate, retry failures, disable expired subscriptions, stop device',()=>{const e=env();e.setStatus(503);e.register({shared:[msg('due','h',Date.now()-1000)]});let d=e.ctx.pushRead_(e.dev);assert.equal(d.lastStatus,503);assert.equal(Object.keys(d.sent).length,0);e.setStatus(201);assert.equal(e.ctx.pushDispatch_(e.dev,true).sent,1);assert.equal(e.ctx.pushDispatch_(e.dev,true).sent,0);e.ctx.push_('uidh','h@test.example',{op:'off',dev:e.dev});assert.equal(e.ctx.pushDispatch_(e.dev,true).sent,0);assert.equal(e.ctx.pushInbox_(e.dev,e.sec).list.length,0);e.setStatus(410);assert.throws(()=>e.register({op:'test'}),/期限切れ/);assert.equal(e.ctx.pushRead_(e.dev).on,false)});
test('immediate additions target partner, respect preferences and survive send failure',()=>{const e=env(),w='d22222222-2222-4222-8222-222222222222';e.register({id:w,uid:'uidw',role:'w'});e.setStatus(503);e.register({now:[msg('added','w',undefined,'add')]});assert.equal(e.ctx.pushRead_(w).now.length,1);assert.equal(e.ctx.pushRead_(e.dev).now.length,0);e.setStatus(201);assert.equal(e.ctx.pushDispatch_(w,true).sent,1);e.register({now:[msg('added','w',undefined,'add')]});assert.equal(e.ctx.pushRead_(w).now.length,0)});
test('weekday and quiet-time policy uses JST, handles midnight, and keeps tests available',()=>{
 const e=env(),p={days:[1,2,3,4,5],quiet:true,start:'22:00',end:'07:00'};
 const at=s=>new Date(s+'+09:00').getTime();
 for(const [s,ok] of [['2026-10-06T06:59:00',false],['2026-10-06T07:00:00',true],['2026-10-06T21:59:00',true],['2026-10-06T22:00:00',false],['2026-10-10T12:00:00',false]])assert.equal(e.ctx.pushAllowed_(p,at(s)),ok);
 assert.equal(e.ctx.pushAllowed_({days:[]},Date.now()),false);e.register();let d=e.ctx.pushRead_(e.dev);d.policy={days:[]};d.now=[{id:'suppressed',at:Date.now(),kind:'add',t:'no',b:''}];e.ctx.pushWrite_(e.dev,d);assert.equal(e.ctx.pushDispatch_(e.dev,true).sent,0);d=e.ctx.pushRead_(e.dev);assert.ok(d.sent[e.ctx.pushId_('suppressed')]);d.now.push({id:'test-manual',at:Date.now(),kind:'test',t:'test',b:''});e.ctx.pushWrite_(e.dev,d);assert.equal(e.ctx.pushDispatch_(e.dev,true).sent,1);
});
test('partner shared updates preserve recipient lead and morning/night times',()=>{
 const e=env(),time=Date.now()+3600000,day=new Date(time+9*3600000).toISOString().slice(0,10);
 const list=[msg('ev:event:'+day+':14:00:60','w',time),{...msg('am:'+day+':w:07:00','w',time,'am')},{...msg('pm:'+day+':w','w',time,'pm')}];
 const transformed=e.ctx.pushShared_(list,'w',{lead:60},{lead:15,am:'23:30',pm:'23:45'});
 assert.equal(transformed.find(x=>x.kind==='ev').at,time+45*60000);assert.equal(transformed.find(x=>x.kind==='am').at,new Date(day+'T23:30:00+09:00').getTime());assert.equal(transformed.find(x=>x.kind==='pm').at,new Date(day+'T23:45:00+09:00').getTime());
});
