const {test}=require('node:test'),assert=require('node:assert/strict'),M=require('../firestore-monitor.js'),O=require('../firestore-offline.js');
const clone=x=>JSON.parse(JSON.stringify(x)),at=s=>Date.parse(s),time=at('2026-10-06T21:33:00Z');
function memory(){let value={paused:false,until:0,entries:[]},chain=Promise.resolve();return {read:async()=>clone(value),update:fn=>{const p=chain.then(()=>{value=clone(fn(clone(value)));return clone(value);});chain=p.catch(()=>{});return p;}};}
function report(t=time,n=123){return {schema:1,project:'p',database:'(default)',checkedAt:t,day:M.dayWindow(t),metrics:{reads:{count:n},writes:{count:null},deletes:{count:0}}};}
function monitor(overrides={}){let now=time,reads=0;const data={},c=M.create({clock:()=>now,project:'p',user:'u',storage:{getItem:k=>data[k],setItem:(k,v)=>data[k]=v},fetchUsage:async()=>{reads++;return report(now);},...overrides});return {c,advance:ms=>now+=ms,reads:()=>reads};}
test('quota days follow Pacific midnight including 23 and 25 hour DST days',()=>{assert.equal(M.dayWindow(time).end,at('2026-10-07T07:00:00Z'));assert.equal(M.dayWindow(at('2026-03-08T15:00:00Z')).end-M.dayWindow(at('2026-03-08T15:00:00Z')).start,23*3600000);assert.equal(M.dayWindow(at('2026-11-01T15:00:00Z')).end-M.dayWindow(at('2026-11-01T15:00:00Z')).start,25*3600000);});
test('monitor shares one request, throttles manual clicks and preserves unknown counts',async()=>{let done;const t=monitor({fetchUsage:()=>new Promise(r=>done=r)}),a=t.c.refresh(true),b=t.c.refresh(true);assert.equal(a,b);await Promise.resolve();done(report());await a;assert.equal(t.c.snapshot().report.metrics.writes.count,null);assert.equal(t.c.snapshot().connected,true);await t.c.refresh(true);assert.equal(t.c.snapshot().loading,false);});
test('monitor shows 80/95/100 percent warnings without claiming stale counts are current',async()=>{for(const [n,level] of [[39999,'unknown'],[40000,'warning'],[47500,'critical'],[50000,'limit']]){const t=monitor({fetchUsage:async()=>report(time,n)});await t.c.refresh(true);assert.equal(t.c.snapshot().level,level);t.advance(601000);assert.equal(t.c.snapshot().stale,true);t.advance(86400000);assert.equal(t.c.snapshot().current,false);assert.equal(t.c.snapshot().level,'unknown');}});
test('API failures retain previous values and setup errors suspend automatic polling',async()=>{let calls=0;const t=monitor({fetchUsage:async()=>{if(++calls===1)return report();throw Error('network down');}});await t.c.refresh(true);t.advance(300000);await t.c.refresh(false);assert.equal(t.c.snapshot().report.metrics.reads.count,123);assert.match(t.c.snapshot().error,/network/);assert.equal(t.c.snapshot().connected,false);let setups=0;const s=monitor({fetchUsage:async()=>{setups++;return {status:'setup_required',setupUrl:'javascript:bad',message:'permission'};}});await s.c.refresh(true);s.advance(300000);await s.c.refresh(false);assert.equal(setups,1);assert.equal(s.c.snapshot().report,null);assert.equal(s.c.snapshot().setupUrl,'');await s.c.refresh(true);assert.equal(setups,2);});
test('monitor does not fetch while backgrounded and rejects foreign or invalid reports',async()=>{let tick;const t=monitor({isVisible:()=>false,setInterval:f=>(tick=f,1),clearInterval(){}});t.c.start();tick();assert.equal(t.reads(),0);t.c.stop();assert.equal(M.validReport(report(),'other'),false);assert.equal(M.validReport({...report(),metrics:{reads:{count:-1}}},'p'),false);});
test('SDK quota is visible without usage access and survives reload until a successful probe',()=>{const data={},opts={clock:()=>time,project:'p',user:'u',storage:{getItem:k=>data[k],setItem:(k,v)=>data[k]=v},fetchUsage:async()=>report()};let c=M.create(opts);c.observeError({code:'resource-exhausted'},'read');c=M.create(opts);assert.equal(c.snapshot().level,'limited');c.clearIssue();assert.equal(c.snapshot().issue,null);});
function offline(overrides={}){let n=0,now=time;const sent=[],store=overrides.store||memory(),c=O.create({project:'p',store,clock:()=>now,id:()=> 'op'+(++n)+Math.random(),dayWindow:M.dayWindow,limited:M.limited,pauseNetwork:async()=>{},resumeNetwork:async()=>{},probe:async()=>{},send:async(...args)=>sent.push(args),...overrides});return {c,sent,store,advance:ms=>now+=ms};}
const quota=()=>Object.assign(Error('quota'),{code:'resource-exhausted'}),doc=data=>({exists:data!==null,data:()=>data,fromCache:true}),col=rows=>({docs:rows.map(([id,d])=>({id,data:()=>d})),metadata:{fromCache:true}});
test('quota mode persists edits, additions and deletes without server writes and restores after restart',async()=>{const t=offline();await t.c.pause(quota());await t.c.write('items/a','update',{text:'変更',nested:{b:2}});await t.c.write('items/b','set',{text:'追加'});await t.c.write('items/c','delete');assert.equal(t.sent.length,0);assert.equal(t.c.snapshot().pending,3);const restored=offline({store:t.store});await restored.c.loaded;assert.equal(restored.c.snapshot().paused,true);const rows=restored.c.overlay('items',col([['a',{text:'元',nested:{a:1}}],['c',{text:'削除対象'}]]),true).docs;assert.deepEqual(rows.map(x=>[x.id,x.data()]),[['a',{text:'変更',nested:{a:1,b:2}}],['b',{text:'追加'}]]);assert.equal(restored.c.overlay('items/b',doc(null),false).data().text,'追加');});
test('a failed server write is durably queued only on quota, not permission errors',async()=>{const t=offline({send:async()=>{throw quota();}});assert.deepEqual(await t.c.write('items/a','set',{text:'保存'}),{local:true});assert.equal(t.c.snapshot().pending,1);const denied=offline({send:async()=>{throw Object.assign(Error('denied'),{code:'permission-denied'});}});await assert.rejects(denied.c.write('items/a','set',{}),/denied/);assert.equal(denied.c.snapshot().pending,0);});
test('recovery probes once, flushes in order and removes only acknowledged operations',async()=>{let probes=0;const t=offline({probe:async()=>probes++});await t.c.pause(quota());await t.c.write('items/a','set',{text:'一'});await t.c.write('items/a','update',{text:'二'});await t.c.resume(false);assert.equal(probes,0);await t.c.resume(true);assert.equal(probes,1);assert.deepEqual(t.sent.map(x=>x[1]),['set','update']);assert.equal(t.c.snapshot().pending,0);assert.equal(t.c.snapshot().paused,false);});
test('failed recovery keeps pending edits and waits before retrying',async()=>{const t=offline({probe:async()=>{throw quota();}});await t.c.pause(quota());await t.c.write('items/a','set',{text:'残す'});await t.c.resume(true);assert.equal(t.c.snapshot().pending,1);assert.equal(t.sent.length,0);assert.equal(t.c.snapshot().until,time+900000);assert.match(t.c.snapshot().error,/端末に残し/);});
test('partial recovery retains the failed and later operations for the next attempt',async()=>{let sends=0;const t=offline({send:async()=>{if(++sends===2)throw Error('offline');}});await t.c.pause(quota());for(let i=0;i<3;i++)await t.c.write('items/'+i,'set',{n:i});await t.c.resume(true);assert.equal(t.c.snapshot().pending,2);assert.deepEqual((await t.c.export()).pendingChanges.map(x=>x.path),['items/1','items/2']);});
test('two open tabs do not send the same queue concurrently',async()=>{const store=memory();let unlock,probes=0,sends=0;const shared={store,probe:async()=>{probes++;await new Promise(r=>unlock=r);},send:async()=>sends++};const a=offline(shared),b=offline(shared);await a.c.pause(quota());await a.c.write('items/a','set',{text:'一度'});const p=a.c.resume(true);while(!unlock)await Promise.resolve();await b.c.resume(true);assert.equal(probes,1);unlock();await p;assert.equal(sends,1);});
test('disk failures never report unsaved changes as locally saved',async()=>{const store=memory(),t=offline({store});await t.c.pause(quota());store.update=async()=>{throw Error('disk full');};await assert.rejects(t.c.write('items/a','set',{}),/保存済みではありません/);assert.equal(t.c.snapshot().pending,0);});
test('nested private paths never appear in a shared collection overlay',async()=>{const t=offline();await t.c.pause(quota());await t.c.write('data/users/u/private/pitems/x','set',{text:'private'});assert.equal(t.c.overlay('items',col([]),true).docs.length,0);assert.equal(t.c.overlay('data/users/other/private/pitems',col([]),true).docs.length,0);});
test('a tab whose queue was recovered elsewhere re-enables its own network',async()=>{let enabled=0;const store=memory(),a=offline({store}),b=offline({store,resumeNetwork:async()=>enabled++});await a.c.pause(quota());await b.c.reload();await a.c.resume(true);await b.c.resume(false);assert.equal(enabled,1);assert.equal(b.c.snapshot().paused,false);});
