const {test}=require('node:test'),assert=require('node:assert/strict'),R=require('../firestore-reads.js'),M=require('../firestore-monitor.js'),vm=require('node:vm'),fs=require('node:fs');
const at=Date.parse('2026-10-07T03:00:00Z');
function storage(){const x=new Map();return {get length(){return x.size;},key:i=>[...x.keys()][i],getItem:k=>x.get(k)||null,setItem:(k,v)=>x.set(k,v),removeItem:k=>x.delete(k)};}
function meter(o={}){let now=at;const s=o.storage||storage(),m=R.create({project:'p',user:'u',session:'s',version:'290',clock:()=>now,storage:s,dayWindow:M.dayWindow,setTimeout:()=>1,...o});return {m,s,advance:n=>now+=n};}
function doc(id,data,meta={}){return {id,data:()=>data,exists:()=>data!==null,metadata:meta};}
function col(list,metadata={}){return {docs:list.map(([id,v])=>doc(id,v)),metadata};}
test('initial listener counts once, cache/promotions/local edits/metadata are separate',()=>{
 const {m}=meter(),l=m.listener('items',true);
 l.snapshot(col([['a',{n:1}],['b',{n:2}]],{fromCache:true}));assert.equal(m.snapshot().total.reads,0);
 assert.equal(l.snapshot(col([['a',{n:1}],['b',{n:2}]])),true);assert.equal(m.snapshot().total.reads,2);
 assert.equal(l.snapshot(col([['a',{n:1}],['b',{n:2}]])),false);assert.equal(m.snapshot().total.reads,2);
 l.snapshot(col([['a',{n:2}],['b',{n:2}]],{hasPendingWrites:true}));assert.equal(m.snapshot().total.reads,2);
 l.snapshot(col([['a',{n:2}],['b',{n:2}]]));assert.equal(m.snapshot().total.reads,3);
 l.snapshot(col([['a',{n:2}]]));assert.equal(m.snapshot().total.reads,3);assert.equal(m.snapshot().total.removed,1);
 assert.equal(m.snapshot().total.cacheDocs,2);assert.equal(m.snapshot().total.localEvents,1);
 l.close();l.close();assert.equal(m.snapshot().active,0);
});
test('empty listener server confirmation is delivered; minimum estimate is one',()=>{const {m}=meter(),l=m.listener('meta/roles',false);l.snapshot(doc('roles',null,{fromCache:true}));assert.equal(l.snapshot(doc('roles',null)),true);assert.equal(m.snapshot().total.initial,1);assert.equal(m.snapshot().total.empty,1);});
test('delta changes do not recount every document in a large collection',()=>{const {m}=meter(),l=m.listener('activity',true),a=Array.from({length:1000},(_,i)=>[String(i),{x:i}]);l.snapshot(col(a));a[1][1]={x:2000};const s=col(a);s.docChanges=()=>[{type:'modified',doc:doc('1',{x:2000})}];l.snapshot(s);assert.equal(m.snapshot().total.reads,1001);assert.equal(m.snapshot().total.updates,1);assert.match(m.snapshot().rows[0].hints.join(),/初回/);});
test('single gets, empty queries, caches and failures are distinguished',async()=>{const {m}=meter();await m.get('blobs/secret-id',false,async()=>doc('secret-id',{data:'private'}));await m.get('blobmeta',true,async()=>col([]));await m.get('blobs/secret-id',false,async()=>doc('secret-id',{}, {fromCache:true}));await assert.rejects(m.get('profiles/private-id',false,async()=>{throw Error('permission');}));const s=m.snapshot();assert.equal(s.total.reads,2);assert.equal(s.total.gets,4);assert.equal(s.total.cacheDocs,1);assert.equal(s.total.errors,1);assert.equal(s.total.unknown,1);assert.doesNotMatch(JSON.stringify(m.export()),/secret-id|private-id|"data"/);});
test('parallel tabs persist independently, reload aggregates, and users stay separate',()=>{const s=storage(),a=meter({storage:s,session:'a'}),b=meter({storage:s,session:'b'});a.m.record('get:music',{reads:3});b.m.record('get:music',{reads:4});a.m.flush();b.m.flush();assert.equal(a.m.snapshot().total.reads,7);const fresh=meter({storage:s,session:'c'});assert.equal(fresh.m.snapshot().total.reads,7);assert.equal(meter({storage:s,user:'other'}).m.snapshot().total.reads,0);});
test('Pacific day rollover and version comparison retain daily diagnostics',()=>{let version='290';const t=meter({version:()=>version});t.m.record('get:music',{reads:3});t.advance(5*3600000);version='291';t.m.record('get:music',{reads:2});assert.equal(t.m.snapshot().total.reads,2);assert.equal(t.m.snapshot(7).total.reads,5);assert.equal(t.m.export().daily.length,2);assert.deepEqual(t.m.snapshot(7).versions.map(v=>v.version),['291','290']);});
test('unavailable storage preserves current diagnostics and marks them unsaved',()=>{const t=meter({storage:{setItem(){throw Error('full');},get length(){throw Error('blocked');}}});t.m.record('get:music',{reads:1});t.m.flush();assert.equal(t.m.snapshot().storageError,true);assert.equal(t.m.snapshot().total.reads,1);});
test('privacy-safe grouping never stores user or document ids',()=>{assert.equal(R.pathKey('data/users/person-123/private/pitems/secret-task'),'private/pitems');assert.equal(R.pathKey('data/users/person-123/prefs'),'private/prefs');assert.equal(R.pathKey('meta/unknown-secret'),'meta/other');assert.equal(R.pathKey('not-whitelisted/id'),'other');});
test('single flight shares only concurrent matching requests and cleans up after errors',async()=>{const one=R.singleFlight();let resolve,calls=0,reused=0;const a=one('x',()=>{calls++;return new Promise(r=>resolve=r);}),b=one('x',()=>{calls++;},()=>reused++);assert.equal(a,b);await Promise.resolve();resolve(5);assert.equal(await b,5);assert.equal(calls,1);assert.equal(reused,1);await assert.rejects(one('x',()=>{throw Error('fail');}));assert.equal(await one('x',()=>6),6);assert.deepEqual(await Promise.all([one('cache',()=>1),one('server',()=>2)]),[1,2]);});
test('legacy gateway calls remain unknown rather than guessed as successful reads',()=>{const {m}=meter();m.remoteAttempt();m.remoteAttempt();const s=m.snapshot();assert.equal(s.total.reads,0);assert.equal(s.total.unknown,2);assert.match(s.rows[0].hints.join(),/サーバー/);});
// Exercise the real shim wrapper, not just counters, with a fake SDK.
const shim=fs.readFileSync(require('node:path').join(__dirname,'../shim.js'),'utf8').split('\n');
function decl(name){const i=shim.findIndex(l=>new RegExp('^  (?:async )?function '+name+'\\(').test(l));for(let j=i;j<shim.length;j++){const s=shim.slice(i,j+1).join('\n');try{new vm.Script(s);return s;}catch{}}throw Error(name);}
test('shim monitors metadata but forwards content and first server confirmation only',()=>{let listener,options,stops=0;const {m}=meter(),seen=[];const c=vm.createContext({fbReads:m,fbWatches:new Set(),fbWatchGroups:new Map(),fbOffline:null,fbError_:()=>{},M:{onSnapshot:(ref,o,cb)=>{options=o;listener=cb;return ()=>stops++;}},colSnap:s=>s,docSnap:s=>s,ref:{path:'items',ref:{}},cb:s=>seen.push(s)});vm.runInContext(decl('fbListen_'),c);const stop=vm.runInContext('fbListen_(ref,true,cb)',c);assert.equal(options.includeMetadataChanges,true);const a=col([['a',{x:1}]],{fromCache:true}),b=col([['a',{x:1}]]);a.docChanges=()=>[{type:'added',doc:doc('a',{x:1})}];b.docChanges=()=>[];listener(a);listener(b);listener(b);assert.equal(seen.length,2);assert.equal(m.snapshot().total.reads,1);stop();assert.equal(stops,1);assert.equal(m.snapshot().active,0);});
test('shim shares simultaneous get calls without losing offline overlay handling',async()=>{const {m}=meter();let calls=0,resolve;const c=vm.createContext({fbReads:m,fbSharedReads:R.singleFlight(),fbOffline:{snapshot:()=>({paused:false}),overlay:(_,s)=>({...s,overlay:true})},M:{getDoc:()=>{calls++;return new Promise(r=>resolve=r);}},colSnap:s=>s,docSnap:s=>s,ref:{path:'music/today',ref:{}}});for(const f of ['fbReadRaw_','fbReadShared_','fbGet_'])vm.runInContext(decl(f),c);const a=vm.runInContext('fbGet_(ref,false)',c),b=vm.runInContext('fbGet_(ref,false)',c);await Promise.resolve();resolve(doc('today',{q:'x'}));assert.equal((await a).overlay,true);assert.equal((await b).overlay,true);assert.equal(calls,1);assert.equal(m.snapshot().total.reads,1);assert.equal(m.snapshot().total.reused,1);});

test('writes and deletes count only SDK acknowledgements, preserve failed attempts and return values',async()=>{const {m}=meter();let done;const p=m.write('items/private-id','set',{text:'秘密'},()=>new Promise(r=>done=r));assert.equal(m.snapshot().total.writes,0);assert.equal(m.snapshot().total.writeAttempts,1);done('ok');assert.equal(await p,'ok');assert.equal(m.snapshot().total.writes,1);await assert.rejects(m.write('items/private-id','delete',null,()=>Promise.reject(Error('quota'))));assert.equal(m.snapshot().total.deletes,0);assert.equal(m.snapshot().total.deleteErrors,1);await m.write('items/private-id','delete',null,async()=>{});assert.equal(m.snapshot().total.deletes,1);assert.equal(m.snapshot().capacity.docs,0);assert.doesNotMatch(JSON.stringify(m.export()),/private-id|秘密/);});
test('document size follows Firestore field types, UTF8 and document name sizing',()=>{const d={type:'Personal',done:false,priority:1,description:'Learn Cloud Firestore'};assert.equal(R.docSize('users/jeff/tasks/my_task_id',d),147);assert.equal(R.valueSize('日'),4);assert.equal(R.valueSize({toUint8Array:()=>new Uint8Array(100)}),100);});
test('capacity deduplicates known documents, handles replacements and removes deleted docs',async()=>{const {m}=meter();await m.get('items/a',false,async()=>doc('a',{text:'long text'}));const before=m.snapshot().capacity.bytes;await m.get('items/a',false,async()=>doc('a',{text:'long text'}));assert.equal(m.snapshot().capacity.bytes,before);await m.write('items/a','update',{done:true},async()=>{});assert.equal(m.snapshot().capacity.docs,0);const l=m.listener('items',true);l.snapshot(col([['a',{x:1}],['b',{x:2}]]));assert.equal(m.snapshot().capacity.docs,2);l.snapshot(col([['b',{x:2}]]));assert.equal(m.snapshot().capacity.docs,1);assert.ok(m.snapshot().capacity.bytes>0);});
test('monthly received size excludes cache events and resets at Pacific calendar month',async()=>{let now=Date.parse('2026-10-31T23:00:00-07:00');const {m}=meter({clock:()=>now});await m.get('items/a',false,async()=>doc('a',{text:'x'},{fromCache:true}));assert.equal(m.snapshot().month.receivedBytes,0);await m.get('items/a',false,async()=>doc('a',{text:'x'}));assert.equal(m.snapshot().month.receivedBytes,R.docSize('items/a',{text:'x'}));now+=2*3600000;assert.equal(m.snapshot().month.receivedBytes,0);assert.equal(m.snapshot(7).total.reads,1);});
test('quota retry queues do not become successful writes until replay acknowledgement',async()=>{const O=require('../firestore-offline.js'),{m}=meter();let r={paused:false,until:0,entries:[]},fail=true;const o=O.create({project:'p',store:{read:async()=>r,update:async f=>(r=f(r))},id:()=>Math.random().toString(),dayWindow:M.dayWindow,limited:M.limited,pauseNetwork:async()=>{},resumeNetwork:async()=>{},probe:async()=>{},send:(p,k,v)=>m.write(p,k,v,async()=>{if(fail)throw {code:'resource-exhausted'};})});await o.write('items/a','set',{text:'x'});assert.equal(o.snapshot().pending,1);assert.equal(m.snapshot().total.writes,0);fail=false;await o.resume(true);assert.equal(m.snapshot().total.writes,1);assert.equal(m.snapshot().total.writeAttempts,2);assert.equal(o.snapshot().pending,0);});
test('all direct Firestore SDK mutations are centralized in the monitored send wrapper',()=>{const src=shim.join('\n');assert.equal((src.match(/M\.setDoc\(/g)||[]).length,1);assert.equal((src.match(/M\.deleteDoc\(/g)||[]).length,1);assert.match(decl('fbSend_'),/fbReads.write/);});

test('write acknowledgements do not erase a newer complete listener snapshot',async()=>{const {m}=meter(),l=m.listener('items',true);l.snapshot(col([['a',{text:'before'}]]));let done;const p=m.write('items/a','update',{text:'after'},()=>new Promise(r=>done=r));l.snapshot(col([['a',{text:'after',full:true}]]));const size=m.snapshot().capacity.bytes;done();await p;assert.equal(m.snapshot().capacity.docs,1);assert.equal(m.snapshot().capacity.bytes,size);});


test('notification writes have explicit shared and private process labels',async()=>{
 const {m}=meter();await m.write('push/device-secret','set',{json:'payload'},async()=>{});await m.write('data/users/u/private/push/device-secret','set',{json:'payload'},async()=>{});
 const rows=m.snapshot().rows;assert.match(rows.find(x=>x.process==='write:push').label,/通知予定/);assert.match(rows.find(x=>x.process==='write:private/push').label,/自分：通知予定/);assert.doesNotMatch(JSON.stringify(m.export()),/device-secret|payload/);
});

function sharedWatchEnv(){
 let sink,onError,starts=0,stops=0;const {m}=meter(),left=[],right=[],errors=[];
 const c=vm.createContext({fbReads:m,fbWatches:new Set(),fbWatchGroups:new Map(),fbOffline:null,fbError_:()=>{},M:{onSnapshot:(_ref,_opts,cb,err)=>{starts++;sink=cb;onError=err;return ()=>stops++;}},colSnap:s=>s,docSnap:s=>s,setTimeout,ref:{path:'activity',ref:{}},left:s=>left.push(s),right:s=>right.push(s),err:e=>errors.push(e)});
 vm.runInContext(decl('fbListen_'),c);return {c,m,left,right,errors,get starts(){return starts;},get stops(){return stops;},emit:s=>sink(s),error:e=>onError(e),run:s=>vm.runInContext(s,c)};
}
test('two history consumers share one read of all 3508 documents without truncation',()=>{
 const t=sharedWatchEnv();t.run('var a=fbListen_(ref,true,left,err);');const rows=Array.from({length:3508},(_,i)=>[String(i),{at:i}]);const first=col(rows);first.docChanges=()=>rows.map(([id,d])=>({type:'added',doc:doc(id,d)}));t.emit(first);
 t.run('var b=fbListen_(ref,true,right,err);');assert.equal(t.starts,1);assert.equal(t.left[0].docs.length,3508);assert.equal(t.right[0].docs.length,3508);assert.equal(t.m.snapshot().total.reads,3508);
 const changed=col(rows.slice(1));changed.docs[0]=doc('1',{at:9999});changed.docChanges=()=>[{type:'removed',doc:doc('0',{at:0})},{type:'modified',doc:doc('1',{at:9999})}];t.emit(changed);
 assert.equal(t.left.at(-1).docs.length,3507);assert.equal(t.right.at(-1).docs[0].data().at,9999);assert.equal(t.m.snapshot().total.reads,3509);
 t.run('a();a();');assert.equal(t.stops,0);t.emit(changed);assert.equal(t.left.length,2);t.run('b();');assert.equal(t.stops,1);assert.equal(t.m.snapshot().active,0);
});
test('shared listeners recover after errors and overlay queued changes for every consumer',()=>{
 const t=sharedWatchEnv();t.run('var a=fbListen_(ref,true,left,err);');t.error(Error('temporary'));assert.equal(t.errors.length,1);t.run('var b=fbListen_(ref,true,right,err);');assert.equal(t.starts,2);
 const s=col([['a',{at:1}]]);s.docChanges=()=>[{type:'added',doc:doc('a',{at:1})}];t.emit(s);
 t.c.fbOffline={overlay:(_path,base)=>({...base,docs:[...base.docs,doc('queued',{at:2})]})};vm.runInContext(decl('fbEmit_'),t.c);t.run('fbEmit_("activity/queued")');assert.equal(t.left.at(-1).docs.length,2);assert.equal(t.right.at(-1).docs.length,2);t.run('a();b()');
});

test('quota sizes are attributed by process, do not sum maxima, and exclude scalar objects from nesting',async()=>{
 const m=R.create({project:'test',user:'test',storage:{getItem(){},setItem(){},length:0},dayWindow:M.dayWindow,setTimeout:()=>1});
 await m.write('diary/hidden-doc','set',{text:'a'.repeat(500),nested:{list:[{value:'x'}]},date:new Date(),bytes:new Uint8Array(16)},async()=>{});
 await m.write('items/hidden-doc','set',{text:'short'},async()=>{});
 const c=m.snapshot(1).capacity,d=c.rows.find(x=>x.group==='diary'),i=c.rows.find(x=>x.group==='items');assert.equal(d.maxDepth,3);assert.equal(i.maxDepth,0);assert.equal(c.maxDoc,d.maxDoc);assert.equal(c.maxField,d.maxField);assert.equal(d.maxField,501);assert(d.maxRequest>i.maxRequest);assert.equal(c.maxRequest,d.maxRequest);assert(!JSON.stringify(c).includes('hidden-doc'));assert(!JSON.stringify(c).includes('a'.repeat(100)));
 await assert.rejects(m.write('comments/failed','set',{text:'attempt'},async()=>{throw Error('network');}));const failed=m.snapshot(1).capacity.rows.find(x=>x.group==='comments');assert.equal(failed.docs,0);assert(failed.maxRequest>0);assert.equal(failed.bytes,0);
});
